# Generated by Django 2.2.6 on 2020-01-08 18:38

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_order', models.IntegerField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga_name', models.CharField(max_length=1000)),
                ('manga_author', models.CharField(max_length=1000)),
                ('manga_illustrator', models.CharField(max_length=1000)),
                ('release_date', models.DateField(verbose_name='date published')),
                ('manga_genre', multiselectfield.db.fields.MultiSelectField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Cyberpunk', 'Cyberpunk'), ('Demons', 'Demons'), ('Drama', 'Drama'), ('Ecchi', 'Ecchi'), ('Fantasy', 'Fantasy'), ('Game', 'Game'), ('Harem', 'Harem'), ('Hentai', 'Hentai'), ('Historical', 'Historical'), ('Horror', 'Horror'), ('Isekai', 'Isekai'), ('Josei', 'Josei'), ('Kids', 'Kids'), ('Magic', 'Magic'), ('Martial Arts', 'Martial Arts'), ('Mecha', 'Mecha'), ('Military', 'Military'), ('Music', 'Music'), ('Mystery', 'Mystery'), ('Parody', 'Parody'), ('Police', 'Police'), ('Post-Apocalyptic', 'Post-Apocalyptic'), ('Psychological', 'Psychological'), ('Reverse Harem', 'Reverse Harem'), ('Romance', 'Romance'), ('School', 'School'), ('Sci-Fi', 'Sci-Fi'), ('Seinen', 'Seinen'), ('Shoujo', 'Shoujo'), ('Shoujo-ai', 'Shoujo-ai'), ('Shounen', 'Shounen'), ('Shounen-ai', 'Shounen-ai'), ('Slice of Life', 'Slice of Life'), ('Space', 'Space'), ('Sports', 'Sports'), ('Super Power', 'Super Power'), ('Supernatural', 'Supernatural'), ('Tragedy', 'Tragedy'), ('Vampire', 'Vampire'), ('Yaoi', 'Yaoi'), ('Yuri', 'Yuri')], default=None, max_length=364)),
                ('manga_score', models.FloatField(default=0.0)),
                ('manga_description', models.TextField(max_length=1000)),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available For Readers')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_order', models.IntegerField(max_length=1000)),
                ('from_manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AiMangaApp.Manga')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_order', models.IntegerField(max_length=1000)),
                ('from_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AiMangaApp.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='from_volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AiMangaApp.Volume'),
        ),
    ]
